# Generated by Django 5.2.4 on 2025-12-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standard_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="alarm",
            table="alarm_manage",
        ),
    ]
